name: test-runner
on:
  pull_request:
    branches: 
      - master
jobs:
  test: 
    name: test
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: test
        run: mvn test